import { ENUM_COMMON } from "@/enum/common";
import { ENUM_PURCHASE } from "@/enum/purchase";
import { CONSTANT_PURCHASE } from "@/constant/purchase";

/**
 * @name ORDER_STATUS_COLOR 订单状态
 */
export const ORDER_STATUS_COLOR = {
  // 待收货
  [ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.TO_BE_RECEIVED]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.DEFAULT,
    text: CONSTANT_PURCHASE.SUPPLIER_ORDER_STATUS.OBJ[
      ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.TO_BE_RECEIVED
    ],
  },
  // 待入库
  [ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.TO_BE_WAREHOUSED]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.WARNING,
    text: CONSTANT_PURCHASE.SUPPLIER_ORDER_STATUS.OBJ[
      ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.TO_BE_WAREHOUSED
    ],
  },
  // 待付款
  [ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.TO_BE_PAID]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.WARNING,
    text: CONSTANT_PURCHASE.SUPPLIER_ORDER_STATUS.OBJ[
      ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.TO_BE_PAID
    ],
  },
  // 完成
  [ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.COMPLETE]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.SUCCESS,
    text: CONSTANT_PURCHASE.SUPPLIER_ORDER_STATUS.OBJ[
      ENUM_PURCHASE.SUPPLIER_ORDER_STATUS.COMPLETE
    ],
  },
};

/**
 * @name ORDER_SETTLEMENT_TYPE 订单结算方式
 */
export const ORDER_SETTLEMENT_TYPE = {
  // 货到付款
  [ENUM_PURCHASE.SUPPLIER_SETTLEMENT.CASH_ON_DELIVERY]: {
    text: CONSTANT_PURCHASE.SUPPLIER_SETTLEMENT.OBJ[
      ENUM_PURCHASE.SUPPLIER_SETTLEMENT.CASH_ON_DELIVERY
    ],
  },
  // 先付款后发货
  [ENUM_PURCHASE.SUPPLIER_SETTLEMENT.DELIVERY_AFTER_PAYMENT]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.WARNING,
    text: CONSTANT_PURCHASE.SUPPLIER_SETTLEMENT.OBJ[
      ENUM_PURCHASE.SUPPLIER_SETTLEMENT.DELIVERY_AFTER_PAYMENT
    ],
  },
};
