import { ENUM_COMMON } from "@/enum/common";
import { ENUM_WAREHOUSE } from "@/enum/warehouse";
import { CONSTANT_WAREHOURE } from "@/constant/warehouse";

/**
 * @name STATUS_COLOR 状态
 */
export const STATUS_COLOR = {
  // 异常
  [ENUM_WAREHOUSE.STATUS.ABNORMAL]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.DANGER,
    text: CONSTANT_WAREHOURE.WAREHOURE_STATUS.OBJ[
      ENUM_WAREHOUSE.STATUS.ABNORMAL
    ],
  },
  // 正常
  [ENUM_WAREHOUSE.STATUS.NORMAL]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.SUCCESS,
    text: CONSTANT_WAREHOURE.WAREHOURE_STATUS.OBJ[ENUM_WAREHOUSE.STATUS.NORMAL],
  },
  // 满载
  [ENUM_WAREHOUSE.STATUS.FULL_LOAD]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.DANGER,
    text: CONSTANT_WAREHOURE.WAREHOURE_STATUS.OBJ[
      ENUM_WAREHOUSE.STATUS.FULL_LOAD
    ],
  },
  // 正在盘点
  [ENUM_WAREHOUSE.STATUS.STOCKTAKING]: {
    color: ENUM_COMMON.STATUS_COLOR_TYPE.WARNING,
    text: CONSTANT_WAREHOURE.WAREHOURE_STATUS.OBJ[
      ENUM_WAREHOUSE.STATUS.STOCKTAKING
    ],
  },
};
