import Head from 'next/head'

import type { NextPage } from 'next'


interface TypeHomeProps {
  user: {
    name: string;
  }
}

const Home: NextPage<TypeHomeProps> = (props) => {
  return (
    <>
      <Head>
        <title>Create App - </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <p className='text-3xl font-bold underline'>Hi</p>
    </>
  )
}

export default Home
